apiVersion: v1
kind: Service
metadata:
  namespace: scraper
  name: scraper-node-service
  labels:
    app: scraper-node-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30211
      name: http
  type: NodePort # debug
  selector:
    app: scraper-node-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: scraper
  name: scraper-node-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper-node-service
  template:
    metadata:
      labels:
        app: scraper-node-service
    spec:
      containers:
        - name: scraper-node-service
          image: tuandung7366/scraper-node:2.0
          ports:
            - containerPort: 3000
              name: http
          # resources:
          #   limits:
          #     cpu: 250m
          #     memory: 250Mi
